### ISSUE TITLE
Node.js single thread with image processing question

### ISSUE THREAD

**Issue by damonYuan** [Turistforeningen/node-s3-uploader#64]
I have use this lib in my project and it works fine in staging. But Image resizing is a cpu intense task, and I can see my staging server cpu usage almost 100% when uploading and resizing a image. Although the staging server is just EC2 t2.micro, I am still afraid that this will lead to server being blocked once pushed to production. (I have tried to upload using two device at the same time and seems to be fine, but still not sure what will happen in production, and the http response takes almost 3000ms!)

Could you tell me how it is handled when multiple users uploading images at the same time and if there is a possibility that the event loop would be blocked which is a big concern in node.js.

My question is also here: 

http://stackoverflow.com/questions/34018487/node-js-with-imagemagick-why-server-is-not-blocked

**Comment by Starefossen** [comment]
This is a great question @damonYuan!

This was a concern for us as well when we created this library. Originally we depended upon `gm` which wraps all the ImageMagick functions for Node.js, this was not very efficient for our case since we had to do `n` resize operations – one for each version of the original image. Hence we created [`im-resize`](https://github.com/Turistforeningen/node-im-resize) which is much more efficient resize of multiple versions using special ImageMagick operations for this purpose.

´im-resize` uses the `exec()` function to execute ImageMagick commands which means that all image processing will run as separate processes and not in the main process which is your Node.js application. If you have multiple CPUs or CPU cores this will happen across all of them according to your operating system's prosess schedular.

If you are on a Linux systems you could run your Node.js application with a high process priority using the `nice` command to ensure that the process will always have priority over other ImageMagic processes. You can also dig deep into ImageMagick internals to see ways to prevent excessive CPU usage, you start by reading [this thread](http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=10847) and the [ImageMagick external resources page](http://www.imagemagick.org/script/resources.php).

Make sure you have reasonable enough CPU and memory for the number of uploads and image versions you are handling, I am reluctant to do premature optimization and introduce more complexity to this library without sufficient data to back up that such an optimization is necessary.

**Comment by damonYuan** [comment]
Cool @Starefossen ! Thanks a lot!
